// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtVLVlv8JvSqsw8sP9YxMWHsqLFDjKAk',
    appId: '1:598863758063:web:23e88d3a3388f61d5ad11a',
    messagingSenderId: '598863758063',
    projectId: 'exchange-admin-69ecb',
    authDomain: 'exchange-admin-69ecb.firebaseapp.com',
    storageBucket: 'exchange-admin-69ecb.firebasestorage.app',
    measurementId: 'G-0N774376FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARmzIPi5ydTQByL9hwXKCNCyapHOPnwaM',
    appId: '1:598863758063:android:d3bb27bfa5844a7a5ad11a',
    messagingSenderId: '598863758063',
    projectId: 'exchange-admin-69ecb',
    storageBucket: 'exchange-admin-69ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0QsgHSGvh-TT0DZ1AgQUepv0V9ItXwyw',
    appId: '1:598863758063:ios:61cac7fe9ddf0ad15ad11a',
    messagingSenderId: '598863758063',
    projectId: 'exchange-admin-69ecb',
    storageBucket: 'exchange-admin-69ecb.firebasestorage.app',
    iosBundleId: 'com.example.exchangeCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0QsgHSGvh-TT0DZ1AgQUepv0V9ItXwyw',
    appId: '1:598863758063:ios:61cac7fe9ddf0ad15ad11a',
    messagingSenderId: '598863758063',
    projectId: 'exchange-admin-69ecb',
    storageBucket: 'exchange-admin-69ecb.firebasestorage.app',
    iosBundleId: 'com.example.exchangeCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXtVLVlv8JvSqsw8sP9YxMWHsqLFDjKAk',
    appId: '1:598863758063:web:62fb35692fd38ee55ad11a',
    messagingSenderId: '598863758063',
    projectId: 'exchange-admin-69ecb',
    authDomain: 'exchange-admin-69ecb.firebaseapp.com',
    storageBucket: 'exchange-admin-69ecb.firebasestorage.app',
    measurementId: 'G-3V69WLTLPZ',
  );
}
